<a href="https://colab.research.google.com/github/rarawulan27/Customer-Segmentation-Insight-Dashboard/blob/main/Copy_of_Welcome_To_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd
import plotly.express as px

In [6]:
from google.colab import files
uploaded = files.upload ()

Saving Flunel Analyst.csv to Flunel Analyst.csv

In [10]:
df = pd.read_csv ("Flunel Analyst.csv")
df.head ()

       user_key event_type                      created_at
0         99359   purchase  2023-01-01 00:00:42.000000 UTC
1  unknown_user    product  2023-01-01 00:25:00.000000 UTC
2         17031       home  2023-01-01 00:25:16.000000 UTC
3         17031    product  2023-01-01 00:29:00.000000 UTC
4         17031       cart  2023-01-01 00:29:45.000000 UTC

In [11]:
df['created_at'] = pd. to_datetime(df['created_at'],errors= 'coerce')

In [12]:
df['user_key'] = df['user_key']. fillna(-1). astype(str)
df.loc[df['user_key'].isna(),'user_key'] = 'guest_' + df.index.astype(str)

In [13]:
funnel_steps = ["home", "product", "cart", "purchase"]

In [14]:
funnel = {}

for step in funnel_steps:
    unique_users = df[df['event_type'] == step]['user_key'].nunique()
    funnel[step] = unique_users

funnel_df = pd.DataFrame(list(funnel.items()), columns=['step', 'unique_users'])
funnel_df

       step  unique_users
0      home          7861
1   product         11041
2      cart         11041
3  purchase         11059

In [17]:
funnel_counts = (
    df.groupby('event_type')['user_key']
    .nunique()
    .reindex(funnel_steps)
    .reset_index()
    .rename(columns={'event_type': 'step', 'user_key': 'unique_users'})
)

funnel_counts

       step  unique_users
0      home          7861
1   product         11041
2      cart         11041
3  purchase         11059

In [18]:
import plotly.express as px

fig = px.funnel(
    funnel_counts,
    x='unique_users',
    y='step',
    color='step'  # supaya warnanya beda-beda
)
fig.show()